### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by marchie** [provisions-group/ms-application-insights-laravel#7]
Hello everyone!

It's been a long time since I wrote this and nearly as long since I've worked with PHP/Laravel - or indeed Application Insights!

It looks like a few people are using this and I've had a couple of pull requests come in (special mentions to @Danthar @enhendrickson @nphmuller ) where I don't know enough about what is going on what the impact will be. 

Is anyone interested in taking over ownership of this from me?

Thanks,

Chris

**Comment by Danthar** [comment]
Sorry, im out. Iv'e moved on since as well.

**Comment by nphmuller** [comment]
Hi Chris. I created the pull requests so we could use your library for our one-off temporary Laravel project. So I don't think I'm the right person to take over ownership.

I'll let you know if the situation changes!

**Comment by enhendrickson** [comment]
@Marchie This is something that I and the Provisions Group team could take on.  We're in both Laravel and Azure quite a bit.  Feel free to contact me here or via email at ehendrickson@provisionsgroup.com.

**Comment by johnwc** [comment]
@Marchie Can you add me as a maintainer. We are in the middle of migrating a fairly large older PHP site over to Laravel 7. We would like to use this and keep it up to date as well.

**Comment by marchie** [comment]
@enhendrickson Apologies - I totally forgot about this and it was only when @johnwc replied that I remembered about it.

Happy to transfer ownership over to you/Provisions if you still want it?

Will add @johnwc as a maintainer now.

**Comment by enhendrickson** [comment]
@Marchie we are ready to take this ... thanks for adding me.  Let me know if you want a more formal transfer.

**Comment by marchie** [comment]
Awesome @enhendrickson - yes please - let's hand it over fully - given it's taken me 18 months to reply to you, it's clear I'm not the right person for the job! 🤦

**Comment by marchie** [comment]
@enhendrickson Do you want me to transfer ownership to @provisions-group ?

**Comment by enhendrickson** [comment]
@Marchie  please do transfer to @provisions-group

**Comment by marchie** [comment]
Thanks @enhendrickson 

I've just tried to transfer it to @provisions-group but I need repository permissions within the organisation - which of course I don't have.

Am I OK to transfer it to you as an individual, and then you can transfer it to @provisions-group?

**Comment by johnwc** [comment]
I have made some updates in my fork of this repo and MS's insight repo to update both for the today's time. Mainly to get it updated to work with L8 and the updated AI v3 JS script. Also to add functionality to be able to config via laravel the client JS options you now can set with v3. We have been testing/using it in our dev site for about a week now.

**Comment by enhendrickson** [comment]
@Marchie  yes, this is a fine approach.  Transfer to me and I'll transfer to provisions group.

**Comment by marchie** [comment]
Thanks @enhendrickson - I think I've done my bit!

**Comment by enhendrickson** [comment]
@Marchie sorry for the delay on my side, but I don't see that you've transferred ownership to me.  When I go to my public repos, I don't see this one.

**Comment by marchie** [comment]
Hey @enhendrickson - here's how it looks to me in the repository settings:

![image](https://user-images.githubusercontent.com/5711374/101243227-9e435680-36f6-11eb-9b26-d8fc33a18a8c.png)

I'll abort it and try again - I believe you should receive an email with a link to click.

**Comment by johnwc** [comment]
@enhendrickson it won't show up in your repo until you accept the transfer.

**Comment by enhendrickson** [comment]
@johnwc  @Marchie so,... I don't see anywhere in the UI to accept it.  Perhaps it won't show up since the original transfer has expired.  @Marchie sorry to make you do this again, but can you cancel and reinitiate the transfer.  I'll watch my email today carefully and make sure that I accept it within the time.

**Comment by marchie** [comment]
@enhendrickson No problem. I have just cancelled and reinitiated it. From what I understand it should come through in an email, but I've not done this before so I'm not sure exactly how it works.

**Comment by enhendrickson** [comment]
@Marchie I think it worked this time.  Thanks!  It says that it's currently transferring.

**Comment by marchie** [comment]
Yep, it's gone from my list of repositories...!

Well... enjoy! Thanks for taking it on.

**Comment by enhendrickson** [comment]
@Marchie   oddly, transferring to my account didn't automatically make me an admin.  I think you might still be the only admin.  Can you try confirming?  If you are, please make me an admin.  I can't see the settings tab so that I can in turn transfer to provisions-group.

**Comment by enhendrickson** [comment]
@Marchie  never mind, apparently it's superficial.  I can get to settings by simply appending "/settings" to the url.  Thanks again.
